[package]
name = "shodan-client"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Shodan client"
repository = "https://github.com/vswarte/shodan-rs"

[dependencies]
url = "2"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.13", features = ["json"] }
